---
title: "Linguistic Data Analysis - Final Project"
author: "Benedict Wuethrich"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

register_stadiamaps(key = "ENTER YOUR OWN KEY HERE",
                    write = FALSE)
```


Everything related to this project can be found in [this GitHub repository](https://github.com/BendixY/LDAR-FP-BW).

```{r packages, include=False}

library(tidyverse)
library(here)
library(ggmap)
library(ggthemes)
library(maps)
library(viridis)
```
#Introduction



#Data Wrangling
The data wrangling for this project was relatively simple, since the datasets provided by WALS and phoible respectively are quite clean already. 
```{r data_wrangling, include=FALSE}
#loading in data from phoible and WALS and limiting them to languages spoken in Australia

phoible <- read_csv(here("data/phoible/phoible.csv")) 
glimpse(phoible)

wals_aus <- read_csv(here("data/WALS/cldf/languages.csv")) %>% 
  filter( #Latitude >= -44 & Latitude <= -11 & 
           #Longitude >= 112 & Longitude <= 154 &
           Macroarea == "Australia")
#boundaries were determined with the help of ChatGPT 4.o but ended up not being helpful enough. i left the code in in case i might need it at another time
glimpse(wals_aus)
```

```{r AUS_map}

map_AUS <- get_stadiamap(bbox = c(left = 112, 
                                  bottom = -44,
                                  right = 154,
                                  top = -11), #here the map boundaries given by ChatGPT earlier came in handy again
                         zoom = 5,
                         maptype = "stamen_toner_lite",
                         color = "color")
ggmap(map_AUS)



map_AUS_family <- ggmap(map_AUS) +
  geom_point(data = wals_aus,
             aes(x = Longitude,
                 y = Latitude,
                 color = Family),
             size = 9) +
  scale_color_colorblind() + #better color
  theme_map() + #removes axes labels and puts the legend in bottom left corner of map
  theme(legend.text = element_text(size = 10),
        legend.title = element_text(size =12)) +
  #        legend.position.inside = c(0.9,0)) + #we can still modify it to our liking 
  labs(color = "Families")
map_AUS_family

ggsave(here("/output/map_AUS_family.png"),
       map_AUS_family,
       width = 30,
       height = 30,
       units = "cm",
       dpi = 600)

```

